### ISSUE TITLE
Missing `package-lock.json` and `.npmignore`

### ISSUE THREAD

**Issue by Rulikkk** [Rulikkk/gatsby-remark-emoji#2]
Looks like all cool repos have that file. Need to figure out which ones I need and why; then add ones I need.

**Comment by b3s23love** [comment]
.npmignore is not needed, and I have just added package-lock.json.

**Comment by b3s23love** [comment]
[Pull request that fixes the issue](https://github.com/Rulikkk/gatsby-remark-emoji/pull/5)

**Comment by b3s23love** [comment]
@Rulikkk, you can now close the issue.
